image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - chmod +x gradlew
  - java -jar .artifacts/app-replan-delivery.jar -port=7777 &


build_script:
  - ./gradlew clean test --info -Dselenide.headless=true
